services:
  - type: web
    name: indiedevuse.com frontend
    runtime: static
    #static sites are free
    #plan: free
    #We rename dist/index.html so that Render can rewrite access to / (which would have an existing file /index.html and it wouldn't rewrite)
    buildCommand: export VITE_RENDER_GIT_COMMIT=$RENDER_GIT_COMMIT && cd frontend && pnpm i && npx puppeteer browsers install chrome && pnpm run build && mv dist/index.html dist/index-default.html
    staticPublishPath: frontend/dist
    routes:
      - type: redirect
        source: /developers/*
        destination: /developer/*
      - type: rewrite
        source: /
        destination: /index-root.html
      - type: rewrite
        source: /about
        destination: /index-about.html
      - type: rewrite
        source: /indie-developer-tech-stacks
        destination: /index-indie-developer-tech-stacks.html
      - type: rewrite
        source: /saas-tech-stack-generator
        destination: /index-saas-tech-stack-generator.html
      - type: rewrite
        source: /developer/hboon
        destination: /index-developer-hboon.html
      - type: rewrite
        source: /developer/devarno
        destination: /index-developer-devarno.html
      - type: rewrite
        source: /developer/bennyqp
        destination: /index-developer-bennyqp.html
      - type: rewrite
        source: /developer/andrei-hudovich
        destination: /index-developer-andrei-hudovich.html
      - type: rewrite
        source: /developer/builditn0w
        destination: /index-developer-builditn0w.html
      - type: rewrite
        source: /developer/dannyt74
        destination: /index-developer-dannyt74.html
      - type: rewrite
        source: /developer/philkellr
        destination: /index-developer-philkellr.html
      - type: rewrite
        source: /developer/chris
        destination: /index-developer-chris.html
      - type: rewrite
        source: /developer/chrisshennan
        destination: /index-developer-chrisshennan.html
      - type: rewrite
        source: /developer/gripfastgameworks
        destination: /index-developer-gripfastgameworks.html
      - type: rewrite
        source: /developer/razvanmuntian
        destination: /index-developer-razvanmuntian.html
      - type: rewrite
        source: /developer/yoanngueny
        destination: /index-developer-yoanngueny.html
      - type: rewrite
        source: /developer/eeoom
        destination: /index-developer-eeoom.html
      - type: rewrite
        source: /developer/mathias-michel
        destination: /index-developer-mathias-michel.html
      - type: rewrite
        source: /developer/jan-lavicka
        destination: /index-developer-jan-lavicka.html
      - type: rewrite
        source: /developer/aleksey-razbakov
        destination: /index-developer-aleksey-razbakov.html
      - type: rewrite
        source: /developer/jouke-siekman
        destination: /index-developer-jouke-siekman.html
      - type: rewrite
        source: /developer/rebecca-owen
        destination: /index-developer-rebecca-owen.html
      - type: rewrite
        source: /developer/kilian-valkhof
        destination: /index-developer-kilian-valkhof.html
      - type: rewrite
        source: /developer/thibault-louis-lucas
        destination: /index-developer-thibault-louis-lucas.html
      - type: rewrite
        source: /developer/marc-lou
        destination: /index-developer-marc-lou.html
      - type: rewrite
        source: /developer/pieter-levels
        destination: /index-developer-pieter-levels.html
      - type: rewrite
        source: /developer/ben-robertson
        destination: /index-developer-ben-robertson.html
      - type: rewrite
        source: /developer/arvid-kahl
        destination: /index-developer-arvid-kahl.html
      - type: rewrite
        source: /developer/joe-masilotti
        destination: /index-developer-joe-masilotti.html
      - type: rewrite
        source: /developer/josh-pigford
        destination: /index-developer-josh-pigford.html
      - type: rewrite
        source: /developer/christoph-miksche
        destination: /index-developer-christoph-miksche.html
      - type: rewrite
        source: /developer/jared-rigby
        destination: /index-developer-jared-rigby.html
      - type: rewrite
        source: /developer/zilvinas-kucinskas
        destination: /index-developer-zilvinas-kucinskas.html
      - type: rewrite
        source: /developer/jakob-greenfeld
        destination: /index-developer-jakob-greenfeld.html
      - type: rewrite
        source: /developer/jon-yongfook
        destination: /index-developer-jon-yongfook.html
      - type: rewrite
        source: /developer/damon-chen
        destination: /index-developer-damon-chen.html
      - type: rewrite
        source: /developer/andrew-culver
        destination: /index-developer-andrew-culver.html
      - type: rewrite
        source: /developer/tony-dinh
        destination: /index-developer-tony-dinh.html
      - type: rewrite
        source: /developer/daniel-nguyen
        destination: /index-developer-daniel-nguyen.html
      - type: rewrite
        source: /developer/dmytro-krasun
        destination: /index-developer-dmytro-krasun.html
      - type: rewrite
        source: /developer/mouad-ennaciri
        destination: /index-developer-mouad-ennaciri.html
      - type: rewrite
        source: /developer/tom-dallimore
        destination: /index-developer-tom-dallimore.html
      - type: rewrite
        source: /developer/rodrigo-rocco
        destination: /index-developer-rodrigo-rocco.html
      - type: rewrite
        source: /developer/uwe-dreissigacker
        destination: /index-developer-uwe-dreissigacker.html
      - type: rewrite
        source: /developer/anton-medviediev
        destination: /index-developer-anton-medviediev.html
      - type: rewrite
        source: /developer/andris-reinman
        destination: /index-developer-andris-reinman.html
      - type: rewrite
        source: /developer/harvey-carpenter
        destination: /index-developer-harvey-carpenter.html
      - type: rewrite
        source: /developer/valerian-de-thezan-de-gaussan
        destination: /index-developer-valerian-de-thezan-de-gaussan.html
      - type: rewrite
        source: /developer/wes-bos
        destination: /index-developer-wes-bos.html
      - type: rewrite
        source: /developer/dominik-schroeter
        destination: /index-developer-dominik-schroeter.html
      - type: rewrite
        source: /developer/adam-wathan
        destination: /index-developer-adam-wathan.html
      - type: rewrite
        source: /developer/ahmad-awais
        destination: /index-developer-ahmad-awais.html
      - type: rewrite
        source: /developer/alexander-isora
        destination: /index-developer-alexander-isora.html
      - type: rewrite
        source: /developer/josh-comeau
        destination: /index-developer-josh-comeau.html
      - type: rewrite
        source: /developer/sindre-sorhus
        destination: /index-developer-sindre-sorhus.html
      - type: rewrite
        source: /developer/jack-mcdade
        destination: /index-developer-jack-mcdade.html
      - type: rewrite
        source: /developer/*
        destination: /index-default.html
      - type: rewrite
        source: /*
        destination: /index-default.html
    domains:
      - indiedevuse.com
    buildFilter:
      paths:
        - frontend/**/*
        - render.yaml
