services:
  - type: web
    name: indiedevuse.com frontend
    runtime: static
    #static sites are free
    #plan: free
    #We rename dist/index.html so that Render can rewrite access to / (which would have an existing file /index.html and it wouldn't rewrite)
    buildCommand: export VITE_RENDER_GIT_COMMIT=$RENDER_GIT_COMMIT && cd frontend && pnpm i && npx puppeteer browsers install chrome && pnpm run build && mv dist/index.html dist/index-default.html
    staticPublishPath: frontend/dist
    routes:
      - type: redirect
        source: /developers/*
        destination: /developer/*
      - type: rewrite
        source: /
        destination: /index-root.html
      - type: rewrite
        source: /about
        destination: /index-about.html
      - type: rewrite
        source: /indie-developer-tech-stacks
        destination: /index-indie-developer-tech-stacks.html
      - type: rewrite
        source: /saas-tech-stack-generator
        destination: /index-saas-tech-stack-generator.html
      - type: rewrite
        source: /developer/hboon
        destination: /index-developer-hboon.html
      - type: rewrite
        source: /developer/devarno
        destination: /index-developer-devarno.html
      - type: rewrite
        source: /developer/bennyqp
        destination: /index-developer-bennyqp.html
      - type: rewrite
        source: /developer/andrei-hudovich
        destination: /index-developer-andrei-hudovich.html
      - type: rewrite
        source: /developer/builditn0w
        destination: /index-developer-builditn0w.html
      - type: rewrite
        source: /developer/dannyt74
        destination: /index-developer-dannyt74.html
      - type: rewrite
        source: /developer/philkellr
        destination: /index-developer-philkellr.html
      - type: rewrite
        source: /developer/chris
        destination: /index-developer-chris.html
      - type: rewrite
        source: /developer/chrisshennan
        destination: /index-developer-chrisshennan.html
      - type: rewrite
        source: /developer/gripfastgameworks
        destination: /index-developer-gripfastgameworks.html
      - type: rewrite
        source: /developer/razvanmuntian
        destination: /index-developer-razvanmuntian.html
      - type: rewrite
        source: /developer/yoanngueny
        destination: /index-developer-yoanngueny.html
      - type: rewrite
        source: /developer/eeoom
        destination: /index-developer-eeoom.html
      - type: rewrite
        source: /developer/mathias-michel
        destination: /index-developer-mathias-michel.html
      - type: rewrite
        source: /developer/*
        destination: /index-default.html
      - type: rewrite
        source: /*
        destination: /index-default.html
    domains:
      - indiedevuse.com
    buildFilter:
      paths:
        - frontend/**/*
        - render.yaml
